#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef DONKEYADSSDKKITRVM_SWIFT_H
#define DONKEYADSSDKKITRVM_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import DonkeyAdsSDKKit;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DonkeyAdsSDKKitRvm",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
enum AssetTypeRvm : NSInteger;
@class NSURL;
@class NSDate;
SWIFT_CLASS_NAMED("AdAssetRvm")
@interface AdAssetRvm : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) enum AssetTypeRvm type;
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
@property (nonatomic, readonly, copy) NSURL * _Nullable link;
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger height;
@property (nonatomic, readonly) NSInteger closeTimeout;
@property (nonatomic, readonly) int64_t filesizeBytes;
@property (nonatomic, readonly) BOOL wifiOnly;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable viewThroughLink;
@property (nonatomic, copy) NSDate * _Nullable lastDownloadTimestamp;
@property (nonatomic) BOOL cachedAtStartup;
@property (nonatomic) NSInteger showCounter;
@property (nonatomic) NSInteger clickCounter;
@property (nonatomic, copy) NSString * _Nullable overrideUrl;
@property (nonatomic, copy) NSString * _Nullable externalTracker;
- (void)incrementShowCounter;
- (void)incrementClickCounter;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, AssetTypeRvm, open) {
  AssetTypeRvmImage = 0,
  AssetTypeRvmVideo = 1,
};

SWIFT_CLASS_NAMED("AdListResponseRvm")
@interface AdListResponseRvm : NSObject
@property (nonatomic, readonly, copy) NSArray<AdAssetRvm *> * _Nonnull adList;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol DonkeyAdsDelegateRvm;
@class UIViewController;
SWIFT_CLASS("_TtC18DonkeyAdsSDKKitRvm8AdSdkRvm")
@interface AdSdkRvm : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double versionNumber;)
+ (double)versionNumber SWIFT_WARN_UNUSED_RESULT;
/// Configures the SDK with the provided client token.
/// @param token The client token for authentication””
+ (void)configureWithToken:(NSString * _Nonnull)token;
/// Configures the SDK with the provided client token and user ID.
/// @param token The client token for authentication
/// @param userId Optional user ID for user-specific targeting
+ (void)configureWithToken:(NSString * _Nonnull)token userId:(NSString * _Nullable)userId;
/// Checks if the SDK has been initialized.
/// @return true if the SDK has been initialized, false otherwise
+ (BOOL)isInitialized SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserId:(NSString * _Nonnull)userId;
+ (void)setDelegate:(id <DonkeyAdsDelegateRvm> _Nullable)delegate;
+ (void)preloadAds;
+ (BOOL)adAvailable SWIFT_WARN_UNUSED_RESULT;
+ (void)showNextAdFrom:(UIViewController * _Nonnull)viewController;
/// Checks if a named ad is available to be shown.
/// @param name The name of the ad to check
/// @return true if the named ad exists and is ready to be shown, false otherwise
+ (BOOL)isNamedAdAvailableWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
/// Shows a specific named ad, optionally overriding its URL and providing an external tracker.
/// @param viewController The view controller to present the ad from
/// @param name The name of the ad to show
/// @param overrideUrl Optional URL to override the ad’s default URL (can be nil)
/// @param externalTracker Optional external tracker URL for reporting (can be nil)
+ (void)showNamedAdFrom:(UIViewController * _Nonnull)viewController name:(NSString * _Nonnull)name overrideUrl:(NSString * _Nullable)overrideUrl externalTracker:(NSString * _Nullable)externalTracker;
/// Shows a specific named ad, optionally overriding its URL.
/// @param viewController The view controller to present the ad from
/// @param name The name of the ad to show
/// @param overrideUrl Optional URL to override the ad’s default URL (can be nil)
+ (void)showNamedAdFrom:(UIViewController * _Nonnull)viewController name:(NSString * _Nonnull)name overrideUrl:(NSString * _Nullable)overrideUrl;
/// Returns a list of loaded assets (full AdAsset objects)
/// @param namedOnly If true, returns only named assets
/// @return Array of AdAsset objects that are currently loaded
+ (NSArray<AdAssetRvm *> * _Nonnull)checkLoadedAssetsWithNamedOnly:(BOOL)namedOnly SWIFT_WARN_UNUSED_RESULT;
/// Returns a list of loaded asset IDs (for backward compatibility)
/// @param namedOnly If true, returns only named assets
/// @return Array of asset IDs that are currently loaded
+ (NSArray<NSString *> * _Nonnull)checkLoadedAssetIdsWithNamedOnly:(BOOL)namedOnly SWIFT_WARN_UNUSED_RESULT;
/// Clears all cached assets and metadata
+ (void)clearCache;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SurveyRvm;
@class NSNumber;
/// Manages the current state of survey answers and progress.
/// Enhanced to support per-question timing and metadata tracking.
SWIFT_CLASS("_TtC18DonkeyAdsSDKKitRvm14AnswerStateRvm")
@interface AnswerStateRvm : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull answers;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// Set an answer for a specific question.
- (void)setAnswerWithQuestionId:(NSString * _Nonnull)questionId answer:(id _Nullable)answer;
/// Get the current answer for a question.
- (id _Nullable)getAnswerWithQuestionId:(NSString * _Nonnull)questionId SWIFT_WARN_UNUSED_RESULT;
/// Check if a question has been answered.
- (BOOL)hasAnswerWithQuestionId:(NSString * _Nonnull)questionId SWIFT_WARN_UNUSED_RESULT;
/// Get all answered question IDs.
- (NSArray<NSString *> * _Nonnull)getAnsweredQuestionIds SWIFT_WARN_UNUSED_RESULT;
/// Get the total number of answered questions.
- (NSInteger)getAnswerCount SWIFT_WARN_UNUSED_RESULT;
/// Clear all answers.
- (void)clearAllAnswers;
/// Remove answer for a specific question.
- (void)removeAnswerWithQuestionId:(NSString * _Nonnull)questionId;
/// Get completion percentage for a survey.
- (double)getCompletionPercentageFor:(SurveyRvm * _Nonnull)survey SWIFT_WARN_UNUSED_RESULT;
/// Check if all required questions in a survey are answered.
- (BOOL)areAllRequiredQuestionsAnsweredFor:(SurveyRvm * _Nonnull)survey SWIFT_WARN_UNUSED_RESULT;
/// Get answers as a dictionary suitable for API submission.
- (NSDictionary<NSString *, id> * _Nonnull)toSubmissionFormat SWIFT_WARN_UNUSED_RESULT;
/// Load answers from a dictionary (e.g., from saved state).
- (void)loadAnswersFrom:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
/// Create a copy of the current answer state.
- (AnswerStateRvm * _Nonnull)clone SWIFT_WARN_UNUSED_RESULT;
/// Start timing for a specific question.
- (void)startQuestionTimingWithQuestionId:(NSString * _Nonnull)questionId;
/// Stop timing for a specific question and record the duration.
- (void)stopQuestionTimingWithQuestionId:(NSString * _Nonnull)questionId;
/// Get the time spent on a specific question in seconds.
- (NSNumber * _Nullable)getQuestionTimeSpentWithQuestionId:(NSString * _Nonnull)questionId SWIFT_WARN_UNUSED_RESULT;
/// Record when a question was answered.
- (void)setAnswerTimestampWithQuestionId:(NSString * _Nonnull)questionId timestamp:(NSDate * _Nonnull)timestamp;
/// Get the timestamp when a question was answered.
- (NSDate * _Nullable)getAnswerTimestampWithQuestionId:(NSString * _Nonnull)questionId SWIFT_WARN_UNUSED_RESULT;
/// Enhanced setAnswer method that also tracks timing.
- (void)setAnswerWithTimingWithQuestionId:(NSString * _Nonnull)questionId answer:(id _Nullable)answer;
@end

@protocol QuestionViewDelegateRvm;
@class QuestionRvm;
SWIFT_PROTOCOL_NAMED("QuestionViewRvm")
@protocol QuestionViewRvm <NSObject>
@property (nonatomic, strong) id <QuestionViewDelegateRvm> _Nullable rvm_delegate;
- (void)rvm_configureWithQuestion:(QuestionRvm * _Nonnull)question answerState:(AnswerStateRvm * _Nonnull)answerState;
- (void)rvm_saveAnswer;
@end

@interface BaseQuestionCard (SWIFT_EXTENSION(DonkeyAdsSDKKitRvm)) <QuestionViewRvm>
@property (nonatomic, strong) id <QuestionViewDelegateRvm> _Nullable rvm_delegate;
- (void)rvm_configureWithQuestion:(QuestionRvm * _Nonnull)question answerState:(AnswerStateRvm * _Nonnull)answerState;
- (void)rvm_saveAnswer;
@end

@class CacheManagerRvm_CacheStats;
SWIFT_CLASS_NAMED("CacheManagerRvm")
@interface CacheManagerRvm : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CacheManagerRvm * _Nonnull shared;)
+ (CacheManagerRvm * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Saves metadata for a single asset
- (void)saveAssetMetadata:(AdAssetRvm * _Nonnull)asset;
- (void)clearAllCachedAssetsAndMetadata;
- (void)clearCache;
- (NSArray<AdAssetRvm *> * _Nonnull)updateAssetListWith:(NSArray<AdAssetRvm *> * _Nonnull)newAssets SWIFT_WARN_UNUSED_RESULT;
/// Removes assets that are no longer in the current server response (outdated assets)
/// while preserving assets that are still valid
- (NSArray<AdAssetRvm *> * _Nonnull)updateAssetListAndCleanupOutdatedWith:(NSArray<AdAssetRvm *> * _Nonnull)newAssets SWIFT_WARN_UNUSED_RESULT;
- (BOOL)finalizeDownloadWithAsset:(AdAssetRvm * _Nonnull)asset sourceURL:(NSURL * _Nonnull)sourceURL isSourceHoldingURL:(BOOL)isSourceHoldingURL SWIFT_WARN_UNUSED_RESULT;
- (void)markDownloadFailedWithAssetId:(NSString * _Nonnull)assetId;
- (NSArray<AdAssetRvm *> * _Nonnull)getReadyAssets SWIFT_WARN_UNUSED_RESULT;
- (NSArray<AdAssetRvm *> * _Nonnull)getLoadedAssetsWithNamedOnly:(BOOL)namedOnly SWIFT_WARN_UNUSED_RESULT;
- (AdAssetRvm * _Nullable)namedAdWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (AdAssetRvm * _Nullable)getNextAd SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasValidCachedAssets SWIFT_WARN_UNUSED_RESULT;
- (NSURL * _Nullable)getFileURLFor:(NSString * _Nonnull)assetId SWIFT_WARN_UNUSED_RESULT;
- (void)performAutomaticCleanup;
- (CacheManagerRvm_CacheStats * _Nonnull)getCacheStats SWIFT_WARN_UNUSED_RESULT;
/// Performs comprehensive cache cleanup for background processing
- (void)performDeepCleanup;
/// Checks if cleanup should be performed based on cache state
- (BOOL)shouldPerformCleanup SWIFT_WARN_UNUSED_RESULT;
/// Gets pending wifi-only assets for background downloading
- (NSArray<AdAssetRvm *> * _Nonnull)getPendingWifiOnlyAssets SWIFT_WARN_UNUSED_RESULT;
/// Gets assets that failed to download for retry attempts
- (NSArray<AdAssetRvm *> * _Nonnull)getFailedDownloadAssets SWIFT_WARN_UNUSED_RESULT;
/// Validates and updates metadata consistency
- (void)validateAndUpdateMetadata;
/// Marks a download as skipped due to network restrictions
- (void)markDownloadSkippedDueToNetworkWithAssetId:(NSString * _Nonnull)assetId;
/// Gets the next available ad (compatibility method)
- (AdAssetRvm * _Nullable)nextAvailableAd SWIFT_WARN_UNUSED_RESULT;
/// Gets the local URL for an asset (compatibility method)
- (NSURL * _Nullable)localURLFor:(AdAssetRvm * _Nonnull)asset SWIFT_WARN_UNUSED_RESULT;
- (AdAssetRvm * _Nullable)getAssetBy:(NSString * _Nonnull)assetId SWIFT_WARN_UNUSED_RESULT;
/// Gets the latest asset from cache to avoid stale data
- (AdAssetRvm * _Nullable)getLatestAssetWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CacheStats")
@interface CacheManagerRvm_CacheStats : NSObject
@property (nonatomic, readonly) NSInteger assetCount;
@property (nonatomic, readonly) int64_t totalSizeBytes;
@property (nonatomic, readonly) NSInteger namedCount;
@property (nonatomic, readonly) NSInteger unnamedCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL_NAMED("DonkeyAdsDelegateRvm")
@protocol DonkeyAdsDelegateRvm <NSObject>
- (void)adsDidLoad;
- (void)adDidShow:(NSString * _Nonnull)assetId impressionHash:(NSString * _Nonnull)impressionHash;
- (void)adDidClick:(NSString * _Nonnull)assetId impressionHash:(NSString * _Nullable)impressionHash;
- (void)adDidClose:(NSString * _Nonnull)assetId impressionHash:(NSString * _Nullable)impressionHash;
@end

SWIFT_CLASS_NAMED("DonkeyAdsLoggerRvm")
@interface DonkeyAdsLoggerRvm : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isEnabled;)
+ (BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
+ (void)log:(NSString * _Nonnull)message from:(NSString * _Nonnull)className;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Utility class for generating unique impression hashes for ad tracking
SWIFT_CLASS_NAMED("ImpressionHasherRvm")
@interface ImpressionHasherRvm : NSObject
/// Generates a unique impression hash based on asset ID, timestamp, and a random element.
/// @param assetId The ID of the ad asset
/// @param timestamp The timestamp of the impression
/// @return A unique hash string for this impression
+ (NSString * _Nonnull)generateImpressionHashWithAssetId:(NSString * _Nonnull)assetId timestamp:(NSDate * _Nonnull)timestamp SWIFT_WARN_UNUSED_RESULT;
/// Validates that a hash looks valid (basic format check)
/// @param hash The hash string to validate
/// @return true if the hash appears to be in a valid format
+ (BOOL)isValidHash:(NSString * _Nonnull)hash SWIFT_WARN_UNUSED_RESULT;
/// Extracts the asset ID from a hash (if it’s in fallback format)
/// @param hash The hash string
/// @return The asset ID if extractable, nil otherwise
+ (NSString * _Nullable)extractAssetIdFrom:(NSString * _Nonnull)hash SWIFT_WARN_UNUSED_RESULT;
/// Extracts the timestamp from a hash (if it’s in fallback format)
/// @param hash The hash string
/// @return The timestamp if extractable, nil otherwise
+ (NSDate * _Nullable)extractTimestampFrom:(NSString * _Nonnull)hash SWIFT_WARN_UNUSED_RESULT;
/// Test method to verify hash generation functionality
/// This method can be used during development to ensure the hasher works correctly
+ (BOOL)runBasicTests SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("LocalizationManagerRvm")
@interface LocalizationManagerRvm : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LocalizationManagerRvm * _Nonnull shared;)
+ (LocalizationManagerRvm * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)setLanguage:(NSString * _Nonnull)languageCode;
- (void)resetToDefault;
- (NSString * _Nonnull)getCurrentLanguage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)localizedStringFor:(NSString * _Nonnull)key params:(NSDictionary<NSString *, NSString *> * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("OptionRvm")
@interface OptionRvm : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic, readonly, copy) NSString * _Nonnull value;
@property (nonatomic, readonly) NSInteger sortOrder;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum QuestionTypeRvm : NSInteger;
SWIFT_CLASS_NAMED("QuestionRvm")
@interface QuestionRvm : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull body;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly) BOOL isRequired;
@property (nonatomic, readonly) NSInteger sortOrder;
@property (nonatomic, readonly, strong) NSNumber * _Nullable sectionId;
@property (nonatomic, readonly, strong) NSNumber * _Nullable minValue;
@property (nonatomic, readonly, strong) NSNumber * _Nullable maxValue;
@property (nonatomic, readonly, strong) NSNumber * _Nullable scaleStart;
@property (nonatomic, readonly, strong) NSNumber * _Nullable scaleEnd;
@property (nonatomic, readonly, copy) NSArray<OptionRvm *> * _Nullable options;
/// Get the question type as an enum.
- (enum QuestionTypeRvm)getQuestionType SWIFT_WARN_UNUSED_RESULT;
/// Check if this is a choice question (single or multi choice).
- (BOOL)isChoiceQuestion SWIFT_WARN_UNUSED_RESULT;
/// Check if this is a scale or rating question.
- (BOOL)isScaleQuestion SWIFT_WARN_UNUSED_RESULT;
/// Get the scale start value, preferring the new field over deprecated one.
- (NSInteger)getScaleQuestionStart SWIFT_WARN_UNUSED_RESULT;
/// Get the scale end value, preferring the new field over deprecated one.
- (NSInteger)getScaleQuestionEnd SWIFT_WARN_UNUSED_RESULT;
/// Get an option by its ID.
- (OptionRvm * _Nullable)getOptionById:(NSInteger)optionId SWIFT_WARN_UNUSED_RESULT;
/// Get an option by its value.
- (OptionRvm * _Nullable)getOptionByValue:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
/// Validate an answer value for this question.
- (BOOL)isValidAnswer:(id _Nullable)answerValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, QuestionTypeRvm, open) {
  QuestionTypeRvmText = 0,
  QuestionTypeRvmSingleChoice = 1,
  QuestionTypeRvmMultiChoice = 2,
  QuestionTypeRvmRating = 3,
  QuestionTypeRvmScale = 4,
};

SWIFT_PROTOCOL_NAMED("QuestionViewDelegateRvm")
@protocol QuestionViewDelegateRvm <NSObject>
- (void)questionView:(id <QuestionViewRvm> _Nonnull)questionView didUpdateAnswer:(id _Nullable)answer for:(NSString * _Nonnull)questionId;
@end

SWIFT_CLASS_NAMED("QuestionViewFactoryRvm")
@interface QuestionViewFactoryRvm : NSObject
/// Create a QuestionView instance for the given question.
+ (id <QuestionViewRvm> _Nullable)createQuestionViewFor:(QuestionRvm * _Nonnull)question SWIFT_WARN_UNUSED_RESULT;
/// Check if a question type is supported.
+ (BOOL)isQuestionTypeSupported:(QuestionRvm * _Nonnull)question SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SectionRvm")
@interface SectionRvm : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable sectionDescription;
@property (nonatomic, readonly) NSInteger sortOrder;
@property (nonatomic, readonly, copy) NSArray<QuestionRvm *> * _Nonnull questions;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents errors that can occur during survey operations.
/// Similar to Android’s SurveyError class.
typedef SWIFT_ENUM_NAMED(NSInteger, SurveyErrorCodeRvm, "SurveyErrorCodeRvm", open) {
  SurveyErrorCodeRvmUnknown = -1,
  SurveyErrorCodeRvmNetworkError = 0,
  SurveyErrorCodeRvmInvalidSurveyData = 1,
  SurveyErrorCodeRvmSurveyNotFound = 2,
  SurveyErrorCodeRvmValidationError = 3,
  SurveyErrorCodeRvmSubmissionFailed = 4,
  SurveyErrorCodeRvmInitializationError = 5,
};

@class SurveySummaryRvm;
@class NSError;
SWIFT_PROTOCOL_NAMED("SurveyLifecycleListenerRvm")
@protocol SurveyLifecycleListenerRvm <NSObject>
/// Called when a survey is started by the user
/// @param survey The survey summary information
- (void)onSurveyStarted:(SurveySummaryRvm * _Nonnull)survey;
/// Called when the user answers a question and moves to the next step
/// @param survey The survey summary information
/// @param state Current answer state with progress information
- (void)onSurveyStepAnswered:(SurveySummaryRvm * _Nonnull)survey :(AnswerStateRvm * _Nonnull)state;
/// Called when the user completes the entire survey
/// @param survey The survey summary information
/// @param rewardPoints Points earned for completing the survey
/// @param state Final answer state with all responses
- (void)onSurveyCompleted:(SurveySummaryRvm * _Nonnull)survey rewardPoints:(NSInteger)rewardPoints :(AnswerStateRvm * _Nonnull)state;
/// Called when the user cancels/exits the survey before completion
/// @param survey The survey summary information
/// @param state Current answer state at time of cancellation
- (void)onSurveyCancelled:(SurveySummaryRvm * _Nonnull)survey :(AnswerStateRvm * _Nonnull)state;
/// Called when an error occurs during survey flow
/// @param survey The survey summary information (may be nil if error occurred before survey loaded)
/// @param error The error that occurred
/// @param state Current answer state at time of error (may be nil)
- (void)onSurveyFailed:(SurveySummaryRvm * _Nullable)survey error:(NSError * _Nonnull)error :(AnswerStateRvm * _Nullable)state;
@end

SWIFT_CLASS_NAMED("SurveyManagerRvm")
@interface SurveyManagerRvm : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SurveyManagerRvm * _Nonnull shared;)
+ (SurveyManagerRvm * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)cacheSurvey:(SurveyRvm * _Nonnull)survey;
- (SurveyRvm * _Nullable)getCachedSurveyWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (NSArray<SurveySummaryRvm *> * _Nonnull)getAvailableSurveys SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSurveyAvailableWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCachedSurveyCount SWIFT_WARN_UNUSED_RESULT;
- (NSSet<NSString *> * _Nonnull)getCachedSurveyIds SWIFT_WARN_UNUSED_RESULT;
- (void)clearCache;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SurveyResponseRvm;
SWIFT_CLASS_NAMED("SurveyNetworkClientRvm")
@interface SurveyNetworkClientRvm : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SurveyNetworkClientRvm * _Nonnull shared;)
+ (SurveyNetworkClientRvm * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)testMultipleEndpointsWithCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, NSNumber *> * _Nonnull))completion;
- (void)testConnectivityWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)fetchSurveyWithExternalKey:(NSString * _Nonnull)externalKey apiToken:(NSString * _Nonnull)apiToken completion:(void (^ _Nonnull)(SurveyRvm * _Nullable, NSError * _Nullable))completion;
- (void)listAvailableSurveysWithApiToken:(NSString * _Nonnull)apiToken completion:(void (^ _Nonnull)(NSArray<NSString *> * _Nullable, NSError * _Nullable))completion;
- (void)submitSurveyResponseWithResponse:(SurveyResponseRvm * _Nonnull)response apiToken:(NSString * _Nonnull)apiToken completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Tracks survey progress and provides analytics.
SWIFT_CLASS_NAMED("SurveyProgressTrackerRvm")
@interface SurveyProgressTrackerRvm : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startSurvey;
- (void)startQuestion:(NSString * _Nonnull)questionId;
- (void)answerQuestion:(NSString * _Nonnull)questionId;
- (NSTimeInterval)getTotalSurveyTime SWIFT_WARN_UNUSED_RESULT;
- (NSTimeInterval)getQuestionAnswerTime:(NSString * _Nonnull)questionId SWIFT_WARN_UNUSED_RESULT;
- (NSTimeInterval)getAverageQuestionTime SWIFT_WARN_UNUSED_RESULT;
- (void)reset;
@end

@class ResponseDataRvm;
/// Complete survey response structure for submission to the FluidData Survey API.
/// Matches the comprehensive format used by Android implementation.
SWIFT_CLASS_NAMED("SurveyResponseRvm")
@interface SurveyResponseRvm : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull apitoken;
@property (nonatomic, readonly, strong) ResponseDataRvm * _Nonnull responseData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AnswerRvm;
/// Main container for survey response submission with metadata and answers.
/// Contains all fields required by FluidData API specification.
SWIFT_CLASS_NAMED("ResponseDataRvm")
@interface ResponseDataRvm : NSObject
@property (nonatomic, readonly) NSInteger surveyId;
@property (nonatomic, readonly, copy) NSString * _Nonnull surveyExternalKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull surveyTitle;
@property (nonatomic, readonly) NSInteger surveyVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
@property (nonatomic, readonly, copy) NSString * _Nullable userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionId;
@property (nonatomic, readonly, copy) NSString * _Nullable ipAddress;
@property (nonatomic, readonly, copy) NSString * _Nullable userAgent;
@property (nonatomic, readonly, copy) NSString * _Nonnull startedAt;
@property (nonatomic, readonly, copy) NSString * _Nullable endTime;
@property (nonatomic, readonly, copy) NSString * _Nonnull completionStatus;
@property (nonatomic, readonly, strong) NSNumber * _Nullable totalTimeSeconds;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceType;
@property (nonatomic, readonly, copy) NSString * _Nullable reportingKey;
@property (nonatomic, readonly, strong) NSNumber * _Nullable customReward;
@property (nonatomic, readonly, copy) NSArray<AnswerRvm *> * _Nonnull answers;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Individual answer object containing question metadata and user response.
/// Includes comprehensive metadata for each answer as required by FluidData API.
SWIFT_CLASS_NAMED("AnswerRvm")
@interface AnswerRvm : NSObject
@property (nonatomic, readonly) NSInteger questionId;
@property (nonatomic, readonly, copy) NSString * _Nonnull questionCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull questionType;
@property (nonatomic, readonly, copy) NSString * _Nonnull questionText;
@property (nonatomic, readonly) NSInteger sortOrder;
@property (nonatomic, readonly) BOOL isRequired;
@property (nonatomic, readonly) id _Nonnull value;
@property (nonatomic, readonly) BOOL skipped;
@property (nonatomic, readonly, strong) NSNumber * _Nullable sectionId;
@property (nonatomic, readonly, copy) NSString * _Nullable sectionTitle;
@property (nonatomic, readonly, strong) NSNumber * _Nullable timeSpentSeconds;
@property (nonatomic, readonly, copy) NSString * _Nullable answeredAt;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Completion status values for survey responses.
typedef SWIFT_ENUM(NSInteger, CompletionStatusRvm, open) {
  CompletionStatusRvmCompleted = 0,
  CompletionStatusRvmPartial = 1,
  CompletionStatusRvmAbandoned = 2,
};

SWIFT_CLASS_NAMED("SurveyRvm")
@interface SurveyRvm : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nullable externalKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nullable surveyDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly) NSInteger rewardPoints;
@property (nonatomic, readonly) NSInteger version;
@property (nonatomic, readonly, copy) NSString * _Nullable languageCode;
@property (nonatomic, readonly, copy) NSArray<SectionRvm *> * _Nullable sections;
@property (nonatomic, readonly, copy) NSArray<QuestionRvm *> * _Nullable questions;
/// Get all questions across all sections.
- (NSArray<QuestionRvm *> * _Nonnull)getAllQuestions SWIFT_WARN_UNUSED_RESULT;
/// Get a question by its ID.
- (QuestionRvm * _Nullable)getQuestionById:(NSInteger)questionId SWIFT_WARN_UNUSED_RESULT;
/// Get a question by its code.
- (QuestionRvm * _Nullable)getQuestionByCode:(NSString * _Nonnull)questionCode SWIFT_WARN_UNUSED_RESULT;
/// Check if this survey is currently active.
- (BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
/// Get the total number of questions in this survey.
- (NSInteger)getTotalQuestionCount SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("SurveySDKRvm")
@interface SurveySDKRvm : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SurveyErrorDomain;)
+ (NSString * _Nonnull)SurveyErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// Get the current survey’s real start time
+ (NSDate * _Nullable)getCurrentSurveyStartTime SWIFT_WARN_UNUSED_RESULT;
/// Initializes the Survey SDK with the FluidData API token
/// @param context The application context (not used in iOS, kept for API compatibility)
/// @param apiToken The FluidData API token for authentication
+ (void)initialize:(id _Nullable)context apiToken:(NSString * _Nonnull)apiToken;
/// Sets the lifecycle listener for survey events
/// @param listener The listener to receive survey events
+ (void)setLifecycleListener:(id <SurveyLifecycleListenerRvm> _Nullable)listener;
/// Tests network connectivity to the API
+ (void)testNetworkConnectivityWithCallback:(void (^ _Nonnull)(BOOL))callback;
/// Tests connectivity to multiple endpoints for debugging
+ (void)debugNetworkConnectivityWithCallback:(void (^ _Nonnull)(NSDictionary<NSString *, NSNumber *> * _Nonnull))callback;
/// Fetches a survey from the backend using its external key
/// @param externalKey The external key of the survey
/// @param callback Callback with the result
/// @param skipConnectivityTest Skip the initial connectivity test (useful for debugging)
+ (void)fetchSurveyFromBackendWithExternalKey:(NSString * _Nonnull)externalKey skipConnectivityTest:(BOOL)skipConnectivityTest callback:(void (^ _Nonnull)(SurveyRvm * _Nullable, NSError * _Nullable))callback;
/// Lists available surveys from the backend (for debugging)
+ (void)listAvailableSurveysWithCallback:(void (^ _Nonnull)(NSArray<NSString *> * _Nullable, NSError * _Nullable))callback;
/// Gets a list of all available surveys
/// @return Array of survey summaries
+ (NSArray<SurveySummaryRvm *> * _Nonnull)getAvailableSurveys SWIFT_WARN_UNUSED_RESULT;
/// Checks if a specific survey is available
/// @param surveyId The ID of the survey to check
/// @return true if the survey is available, false otherwise
+ (BOOL)isSurveyAvailable:(NSString * _Nonnull)surveyId SWIFT_WARN_UNUSED_RESULT;
/// Creates a test survey for development purposes
/// This creates a comprehensive survey with all question types across multiple sections
+ (void)createTestSurvey;
/// Start a survey with the given ID from the presenting view controller
+ (void)startSurveyFrom:(UIViewController * _Nonnull)viewController surveyId:(NSString * _Nonnull)surveyId reportingKey:(NSString * _Nullable)reportingKey customReward:(NSNumber * _Nullable)customReward themeOverride:(NSString * _Nullable)themeOverride orientationOverride:(NSString * _Nullable)orientationOverride;
/// Start a survey with external key from the presenting view controller
+ (void)startSurveyFrom:(UIViewController * _Nonnull)viewController externalKey:(NSString * _Nonnull)externalKey reportingKey:(NSString * _Nullable)reportingKey customReward:(NSNumber * _Nullable)customReward themeOverride:(NSString * _Nullable)themeOverride orientationOverride:(NSString * _Nullable)orientationOverride;
/// Clears the survey cache
+ (void)clearCache;
/// Gets the number of cached surveys
/// @return Number of surveys in cache
+ (NSInteger)getCachedSurveyCount SWIFT_WARN_UNUSED_RESULT;
/// Gets the IDs of all cached surveys
/// @return Set of survey IDs
+ (NSSet<NSString *> * _Nonnull)getCachedSurveyIds SWIFT_WARN_UNUSED_RESULT;
/// Sets the language for the survey UI
/// @param languageCode Language code (“de” for German, “en” for English)
+ (void)setLanguage:(NSString * _Nonnull)languageCode;
/// Resets the language to default (German)
+ (void)resetLanguageToDefault;
/// Gets the current language code
/// @return Current language code
+ (NSString * _Nonnull)getCurrentLanguage SWIFT_WARN_UNUSED_RESULT;
/// Submit a survey response to the FluidData API.
/// This method handles the submission of comprehensive survey responses.
+ (void)submitSurveyResponse:(SurveyResponseRvm * _Nonnull)response completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Create a comprehensive FluidData survey response from survey data and answers.
/// This method builds the complete response structure required by the FluidData API.
+ (SurveyResponseRvm * _Nonnull)createSurveyResponseWithSurvey:(SurveyRvm * _Nonnull)survey answers:(NSDictionary<NSString *, id> * _Nonnull)answers reportingKey:(NSString * _Nullable)reportingKey customReward:(NSNumber * _Nullable)customReward startTime:(NSDate * _Nonnull)startTime userId:(NSString * _Nullable)userId SWIFT_WARN_UNUSED_RESULT;
/// Enhanced createSurveyResponse that accepts AnswerState for timing information.
+ (SurveyResponseRvm * _Nonnull)createSurveyResponseWithSurvey:(SurveyRvm * _Nonnull)survey answerState:(AnswerStateRvm * _Nonnull)answerState reportingKey:(NSString * _Nullable)reportingKey customReward:(NSNumber * _Nullable)customReward startTime:(NSDate * _Nonnull)startTime userId:(NSString * _Nullable)userId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Summary information about a survey.
/// Similar to Android’s SurveySummary class.
SWIFT_CLASS_NAMED("SurveySummaryRvm")
@interface SurveySummaryRvm : NSObject
@property (nonatomic, readonly) NSInteger surveyId;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nullable sumaryDescription;
@property (nonatomic, readonly) NSInteger totalQuestions;
@property (nonatomic, readonly) NSInteger totalSections;
@property (nonatomic, readonly) NSInteger rewardPoints;
@property (nonatomic, readonly, strong) NSNumber * _Nullable estimatedDurationMinutes;
@property (nonatomic, readonly, copy) NSString * _Nullable languageCode;
@property (nonatomic, readonly, copy) NSString * _Nullable externalKey;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SurveyThemeManagerRvm_Theme : NSInteger;
@class UIView;
@class UIColor;
/// Manages survey theming to match Android implementation.
SWIFT_CLASS("_TtC18DonkeyAdsSDKKitRvm21SurveyThemeManagerRvm")
@interface SurveyThemeManagerRvm : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SurveyThemeManagerRvm * _Nonnull shared;)
+ (SurveyThemeManagerRvm * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) enum SurveyThemeManagerRvm_Theme currentTheme;
- (void)applyTheme:(enum SurveyThemeManagerRvm_Theme)theme to:(UIView * _Nonnull)view;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull cardBackgroundColor;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SurveyThemeManagerRvm_Theme, "ThemeRvm", open) {
  SurveyThemeManagerRvm_ThemeLight = 0,
  SurveyThemeManagerRvm_ThemeDark = 1,
  SurveyThemeManagerRvm_ThemeAuto = 2,
};

@class ValidationErrorRvm;
/// Helper class for validating survey responses.
SWIFT_CLASS_NAMED("SurveyValidationHelperRvm")
@interface SurveyValidationHelperRvm : NSObject
+ (NSArray<ValidationErrorRvm *> * _Nonnull)validateAnswerState:(AnswerStateRvm * _Nonnull)answerState for:(SurveyRvm * _Nonnull)survey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SurveyViewController (SWIFT_EXTENSION(DonkeyAdsSDKKitRvm))
- (void)rvm_noop;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RVM_EXTRA_SURVEY_ID;)
+ (NSString * _Nonnull)RVM_EXTRA_SURVEY_ID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RVM_EXTRA_REPORTING_KEY;)
+ (NSString * _Nonnull)RVM_EXTRA_REPORTING_KEY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RVM_EXTRA_CUSTOM_REWARD;)
+ (NSString * _Nonnull)RVM_EXTRA_CUSTOM_REWARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RVM_EXTRA_THEME_OVERRIDE;)
+ (NSString * _Nonnull)RVM_EXTRA_THEME_OVERRIDE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RVM_EXTRA_ORIENTATION_OVERRIDE;)
+ (NSString * _Nonnull)RVM_EXTRA_ORIENTATION_OVERRIDE SWIFT_WARN_UNUSED_RESULT;
/// Set the survey data for this view controller
- (void)rvm_setSurvey:(SurveyRvm * _Nonnull)survey;
/// Get the real start time when the survey was displayed to the user
- (NSDate * _Nullable)rvm_getSurveyStartTime SWIFT_WARN_UNUSED_RESULT;
@end

enum ValidationErrorTypeRvm : NSInteger;
SWIFT_CLASS_NAMED("ValidationErrorRvm")
@interface ValidationErrorRvm : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull questionId;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly) enum ValidationErrorTypeRvm type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ValidationErrorTypeRvm, "ValidationErrorTypeRvm", open) {
  ValidationErrorTypeRvmRequired = 0,
  ValidationErrorTypeRvmInvalidFormat = 1,
  ValidationErrorTypeRvmOutOfRange = 2,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
